### ISSUE TITLE
META: results with emscripten assertion checking on

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#189]
The default `emscripten` build flags appear to be focused more on keeping the produced files small and on performance. Some of the checks/assertions are skipped and exceptions are not caught. 

In this issue I report the result of the test suite when enabling more debug flags / assertion checking,
```
  -s ASSERTIONS=2 \
  -s SAFE_HEAP=1 \
  -s EXCEPTION_DEBUG=1 \
  -s DISABLE_EXCEPTION_CATCHING=0 \
  -s ERROR_ON_UNDEFINED_SYMBOLS=1 \
  -s "BINARYEN_TRAP_MODE='clamp'"
```
added both to `LDFLAGS` and `SIDE_LDFLAGS` (for good measure) passed to emscripten.

With these options using Firefox there are 43 failed tests (out of 455) full log can be found in [pyodide-tests-debug-flags.log](https://github.com/iodide-project/pyodide/files/2415996/pyodide-tests-debug-flags.log). Not all errors / warnings are probably important, but some may be informative for errors reported in other issues.

 - [ ] LinkError: import object field '___cxa_find_matching_catch_14' is not a Function #191
 - [x] Segmentation fault in test_unicode_file in syscall320 (utimensat) #192
 - [x] Calling stub instead of sigaction warning #190

Although setting these flags overall makes the output files larger (by ~40% LZ4 compressed) and the test suite runs much slower as a result (by a factor of 5 times), if might be worth considering including some of the less costly ones in the default settings, in particular,
``` 
-s "BINARYEN_TRAP_MODE='clamp'"
-s ERROR_ON_UNDEFINED_SYMBOLS=1   # this will be enabled by default in emscripten
```

**Comment by mdboom** [comment]
We could also consider adding these in a separate Circle-CI build that doesn't get deployed (so runtime isn't as important).  Though maybe that's only helpful once we clean out all of the failures...

**Comment by rth** [comment]
We could, for instance, do it in a [Circle CI cron job](https://circleci.com/docs/2.0/workflows/#nightly-example) once most problematic failures are understood, so it doesn't delay PRs.

**Comment by mdboom** [comment]
I didn't realize you could do that with Circle CI.  I've used Travis for most of my projects in the past, but I'm really impressed with Circle CI in general...

**Comment by rth** [comment]
Closing this, as the only remaining issue here,
> LinkError: import object field '___cxa_find_matching_catch_14' is not a Function #191

has a dedicated issue (and is possibly not critical).
