### ISSUE TITLE
META: matplotlib issues

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#31]
- [ ] Interactivity -- need to write a new HTML Canvas-based backend
- [ ] tri module -- skipped for now due to some compilation issues
- [ ] qhull module -- skipped for now due to some compilation issues
- [ ] custom fonts -- for now, it only has access to the "shipped" fonts
